using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PrinterStubC.CInterface
{
    //------------------------------------------------------------------------------
//  功能码所属层级定义
//------------------------------------------------------------------------------
    public enum GX_FEATURE_LEVEL : int
    {
        REMOTE_DEV = 0x00000000,

        ///< RemoteDevice层
        TL = 0x01000000,

        ///< TL层
        IF = 0x02000000,

        ///< Interface层	
        DEV = 0x03000000,

        ///< Device层
        DS = 0x04000000, ///< DataStream层
    }

//------------------------------------------------------------------------------
//  功能码类型定义
//------------------------------------------------------------------------------
    public enum GX_FEATURE_TYPE : int
    {
        INT = 0x10000000,

        ///< 整型数
        FLOAT = 0X20000000,

        ///< 浮点数
        ENUM = 0x30000000,

        ///< 枚举
        BOOL = 0x40000000,

        ///< 布尔
        STRING = 0x50000000,

        ///< 字符串
        BUFFER = 0x60000000,

        ///< buffer
        COMMAND = 0x70000000, ///< 命令
    }

    public enum GX_FEATURE_ID : int
    {
        //////////////////////////////////////////////////////////////////////////
        /// 远端设备层(Remote Device Feature)
        //////////////////////////////////////////////////////////////////////////

        //---------------DeviceInfomation Section--------------------------
        GX_STRING_DEVICE_VENDOR_NAME = 0 | GX_FEATURE_TYPE.STRING | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 厂商名称
        GX_STRING_DEVICE_MODEL_NAME = 1 | GX_FEATURE_TYPE.STRING | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 设备型号
        GX_STRING_DEVICE_FIRMWARE_VERSION = 2 | GX_FEATURE_TYPE.STRING | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 设备固件版本
        GX_STRING_DEVICE_VERSION = 3 | GX_FEATURE_TYPE.STRING | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 设备版本
        GX_STRING_DEVICE_SERIAL_NUMBER = 4 | GX_FEATURE_TYPE.STRING | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 设备序列号
        GX_STRING_FACTORY_SETTING_VERSION = 6 | GX_FEATURE_TYPE.STRING | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 出厂参数版本
        GX_STRING_DEVICE_USERID = 7 | GX_FEATURE_TYPE.STRING | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 用户自定义名称
        GX_INT_DEVICE_LINK_SELECTOR = 8 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 设备链路选择
        GX_ENUM_DEVICE_LINK_THROUGHPUT_LIMIT_MODE = 9 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 设备带宽限制模式，参考GX_DEVICE_LINK_THROUGHPUT_LIMIT_MODE_ENTRY
        GX_INT_DEVICE_LINK_THROUGHPUT_LIMIT = 10 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 设备链路带宽限制
        GX_INT_DEVICE_LINK_CURRENT_THROUGHPUT = 11 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 当前设备采集带宽


        //---------------ImageFormat Section--------------------------------
        GX_INT_SENSOR_WIDTH = 1000 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 传感器宽度
        GX_INT_SENSOR_HEIGHT = 1001 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 传感器高度
        GX_INT_WIDTH_MAX = 1002 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 最大宽度
        GX_INT_HEIGHT_MAX = 1003 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 最大高度
        GX_INT_OFFSET_X = 1004 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 水平偏移
        GX_INT_OFFSET_Y = 1005 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 垂直偏移
        GX_INT_WIDTH = 1006 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 图像宽度
        GX_INT_HEIGHT = 1007 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 图像高度
        GX_INT_BINNING_HORIZONTAL = 1008 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 水平像素Binning
        GX_INT_BINNING_VERTICAL = 1009 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 垂直像素Binning
        GX_INT_DECIMATION_HORIZONTAL = 1010 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 水平像素抽样
        GX_INT_DECIMATION_VERTICAL = 1011 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 垂直像素抽样
        GX_ENUM_PIXEL_SIZE = 1012 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 像素位深,参考GX_PIXEL_SIZE_ENTRY
        GX_ENUM_PIXEL_COLOR_FILTER = 1013 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< Bayer格式,参考GX_PIXEL_COLOR_FILTER_ENTRY
        GX_ENUM_PIXEL_FORMAT = 1014 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 像素格式,参考GX_PIXEL_FORMAT_ENTRY
        GX_BOOL_REVERSE_X = 1015 | GX_FEATURE_TYPE.BOOL | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 水平翻转
        GX_BOOL_REVERSE_Y = 1016 | GX_FEATURE_TYPE.BOOL | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 垂直翻转
        GX_ENUM_TEST_PATTERN = 1017 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 测试图,参考GX_TEST_PATTERN_ENTRY
        GX_ENUM_TEST_PATTERN_GENERATOR_SELECTOR = 1018 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 测试图源选择，参考GX_TEST_PATTERN_GENERATOR_SELECTOR_ENTRY


        //---------------TransportLayer Section-------------------------------
        GX_INT_PAYLOAD_SIZE = 2000 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 数据大小 
        GX_BOOL_GEV_CURRENT_IPCONFIGURATION_LLA = 2001 | GX_FEATURE_TYPE.BOOL | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< LLA方式配置IP
        GX_BOOL_GEV_CURRENT_IPCONFIGURATION_DHCP = 2002 | GX_FEATURE_TYPE.BOOL | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< DHCP方式配置IP
        GX_BOOL_GEV_CURRENT_IPCONFIGURATION_PERSISTENTIP = 2003 | GX_FEATURE_TYPE.BOOL | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 永久IP方式配置IP
        GX_INT_ESTIMATED_BANDWIDTH = 2004 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 预估带宽，单位Bps(Bytes per second)
        GX_INT_GEV_HEARTBEAT_TIMEOUT = 2005 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 心跳超时时间
        GX_INT_GEV_PACKETSIZE = 2006 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 流通道包长
        GX_INT_GEV_PACKETDELAY = 2007 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 流通道包间隔
        GX_INT_GEV_LINK_SPEED = 2008 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 连接速度

        //---------------AcquisitionTrigger Section---------------------------
        GX_ENUM_ACQUISITION_MODE = 3000 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 采集模式,参考GX_ACQUISITION_MODE_ENTRY
        GX_COMMAND_ACQUISITION_START = 3001 | GX_FEATURE_TYPE.COMMAND | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 开始采集
        GX_COMMAND_ACQUISITION_STOP = 3002 | GX_FEATURE_TYPE.COMMAND | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 停止采集
        GX_INT_ACQUISITION_SPEED_LEVEL = 3003 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 采集速度级别
        GX_INT_ACQUISITION_FRAME_COUNT = 3004 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 多帧采集帧数
        GX_ENUM_TRIGGER_MODE = 3005 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 触发模式,参考GX_TRIGGER_MODE_ENTRY
        GX_COMMAND_TRIGGER_SOFTWARE = 3006 | GX_FEATURE_TYPE.COMMAND | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 软触发
        GX_ENUM_TRIGGER_ACTIVATION = 3007 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 触发极性,参考GX_TRIGGER_ACTIVATION_ENTRY
        GX_ENUM_TRIGGER_SWITCH = 3008 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 外触发开关,参考GX_TRIGGER_SWITCH_ENTRY
        GX_FLOAT_EXPOSURE_TIME = 3009 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 曝光时间
        GX_ENUM_EXPOSURE_AUTO = 3010 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动曝光,参考GX_EXPOSURE_AUTO_ENTRY
        GX_FLOAT_TRIGGER_FILTER_RAISING = 3011 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 上升沿触发滤波
        GX_FLOAT_TRIGGER_FILTER_FALLING = 3012 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 下降沿触发滤波
        GX_ENUM_TRIGGER_SOURCE = 3013 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 触发源,参考GX_TRIGGER_SOURCE_ENTRY
        GX_ENUM_EXPOSURE_MODE = 3014 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 曝光模式，参考GX_EXPOSURE_MODE_ENTRY
        GX_ENUM_TRIGGER_SELECTOR = 3015 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 触发类型选择，参考GX_TRIGGER_SELECTOR_ENTRY
        GX_FLOAT_TRIGGER_DELAY = 3016 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 触发延迟
        GX_ENUM_TRANSFER_CONTROL_MODE = 3017 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 传输控制模式，参考GX_TRANSFER_CONTROL_MODE_ENTRY
        GX_ENUM_TRANSFER_OPERATION_MODE = 3018 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 传输操作模式，参考GX_TRANSFER_OPERATION_MODE_ENTRY
        GX_COMMAND_TRANSFER_START = 3019 | GX_FEATURE_TYPE.COMMAND | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 开始传输
        GX_INT_TRANSFER_BLOCK_COUNT = 3020 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 传输帧数。当GX_ENUM_TRANSFER_OPERATION_MODE设置为GX_ENUM_TRANSFER_OPERATION_MODE_MULTIBLOCK模式的时候此功能被激活
        GX_BOOL_FRAMESTORE_COVER_ACTIVE = 3021 | GX_FEATURE_TYPE.BOOL | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 帧存覆盖使能


        //----------------DigitalIO Section----------------------------------
        GX_ENUM_USER_OUTPUT_SELECTOR = 4000 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 用户自定义输出选择,参考GX_USER_OUTPUT_SELECTOR_ENTRY
        GX_BOOL_USER_OUTPUT_VALUE = 4001 | GX_FEATURE_TYPE.BOOL | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 用户自定义输出值
        GX_ENUM_USER_OUTPUT_MODE = 4002 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 用户IO输出模式,参考GX_USER_OUTPUT_MODE_ENTRY
        GX_ENUM_STROBE_SWITCH = 4003 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 闪光灯开关,参考GX_STROBE_SWITCH_ENTRY
        GX_ENUM_LINE_SELECTOR = 4004 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 引脚选择,参考GX_LINE_SELECTOR_ENTRY
        GX_ENUM_LINE_MODE = 4005 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 引脚方向,参考GX_LINE_MODE_ENTRY
        GX_BOOL_LINE_INVERTER = 4006 | GX_FEATURE_TYPE.BOOL | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 引脚电平反转
        GX_ENUM_LINE_SOURCE = 4007 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 引脚输出源,参考GX_LINE_SOURCE_ENTRY
        GX_BOOL_LINE_STATUS = 4008 | GX_FEATURE_TYPE.BOOL | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 引脚状态
        GX_INT_LINE_STATUS_ALL = 4009 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 所有引脚的状态

        //----------------AnalogControls Section----------------------------
        GX_ENUM_GAIN_AUTO = 5000 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动增益,参考GX_GAIN_AUTO_ENTRY
        GX_ENUM_GAIN_SELECTOR = 5001 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 增益通道选择,参考GX_GAIN_SELECTOR_ENTRY	
        GX_ENUM_BLACKLEVEL_AUTO = 5003 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动黑电平,参考GX_BLACKLEVEL_AUTO_ENTRY
        GX_ENUM_BLACKLEVEL_SELECTOR = 5004 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 黑电平通道选择,参考GX_BLACKLEVEL_SELECTOR_ENTRY	
        GX_ENUM_BALANCE_WHITE_AUTO = 5006 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动白平衡,参考GX_BALANCE_WHITE_AUTO_ENTRY
        GX_ENUM_BALANCE_RATIO_SELECTOR = 5007 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 白平衡通道选择,参考GX_BALANCE_RATIO_SELECTOR_ENTRY
        GX_FLOAT_BALANCE_RATIO = 5008 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 白平衡系数
        GX_ENUM_COLOR_CORRECT = 5009 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 颜色校正,参考GX_COLOR_CORRECT_ENTRY
        GX_ENUM_DEAD_PIXEL_CORRECT = 5010 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 坏点校正,参考GX_DEAD_PIXEL_CORRECT_ENTRY
        GX_FLOAT_GAIN = 5011 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 增益
        GX_FLOAT_BLACKLEVEL = 5012 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 黑电平

        //---------------CustomFeature Section-------------------------
        GX_INT_ADC_LEVEL = 6000 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< AD转换级别
        GX_INT_H_BLANKING = 6001 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 水平消隐
        GX_INT_V_BLANKING = 6002 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 垂直消隐
        GX_STRING_USER_PASSWORD = 6003 | GX_FEATURE_TYPE.STRING | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 用户加密区密码
        GX_STRING_VERIFY_PASSWORD = 6004 | GX_FEATURE_TYPE.STRING | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 用户加密区校验密码
        GX_BUFFER_USER_DATA = 6005 | GX_FEATURE_TYPE.BUFFER | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 用户加密区内容
        GX_INT_GRAY_VALUE = 6006 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 期望灰度值
        GX_ENUM_AA_LIGHT_ENVIRONMENT = 6007 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动曝光、自动增益，光照环境类型,参考GX_AA_LIGHT_ENVIRMENT_ENTRY
        GX_INT_AAROI_OFFSETX = 6008 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动调节感兴趣区域X坐标
        GX_INT_AAROI_OFFSETY = 6009 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动调节感兴趣区域Y坐标
        GX_INT_AAROI_WIDTH = 6010 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动调节感兴趣区域宽度
        GX_INT_AAROI_HEIGHT = 6011 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动调节感兴趣区域高度
        GX_FLOAT_AUTO_GAIN_MIN = 6012 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动增益最小值
        GX_FLOAT_AUTO_GAIN_MAX = 6013 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动增益最大值
        GX_FLOAT_AUTO_EXPOSURE_TIME_MIN = 6014 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动曝光最小值
        GX_FLOAT_AUTO_EXPOSURE_TIME_MAX = 6015 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动曝光最大值
        GX_BUFFER_FRAME_INFORMATION = 6016 | GX_FEATURE_TYPE.BUFFER | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 图像帧信息
        GX_INT_CONTRAST_PARAM = 6017 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 对比度参数
        GX_FLOAT_GAMMA_PARAM = 6018 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 伽马参数
        GX_INT_COLOR_CORRECTION_PARAM = 6019 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 颜色校正系数
        GX_ENUM_IMAGE_GRAY_RAISE_SWITCH = 6020 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 图像亮度拉伸开关,参考GX_IMAGE_GRAY_RAISE_SWITCH_ENTRY
        GX_ENUM_AWB_LAMP_HOUSE = 6021 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动白平衡光源,参考GX_AWB_LAMP_HOUSE_ENTRY
        GX_INT_AWBROI_OFFSETX = 6022 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动白平衡感兴趣区域X坐标
        GX_INT_AWBROI_OFFSETY = 6023 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动白平衡感兴趣区域Y坐标
        GX_INT_AWBROI_WIDTH = 6024 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动白平衡感兴趣区域宽度
        GX_INT_AWBROI_HEIGHT = 6025 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动白平衡感兴趣区域高度

        //---------------UserSetControl Section-------------------------
        GX_ENUM_USER_SET_SELECTOR = 7000 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 参数组选择,参考GX_USER_SET_SELECTOR_ENTRY
        GX_COMMAND_USER_SET_LOAD = 7001 | GX_FEATURE_TYPE.COMMAND | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 加载参数组
        GX_COMMAND_USER_SET_SAVE = 7002 | GX_FEATURE_TYPE.COMMAND | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 保存参数组
        GX_ENUM_USER_SET_DEFAULT = 7003 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 启动参数组,参考GX_USER_SET_DEFAULT_ENTRY

        //---------------Event Section-------------------------
        GX_ENUM_EVENT_SELECTOR = 8000 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 事件源选择,参考GX_EVENT_SELECTOR_ENTRY
        GX_ENUM_EVENT_NOTIFICATION = 8001 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 事件使能,参考GX_EVENT_NOTIFICATION_ENTRY
        GX_INT_EVENT_EXPOSUREEND = 8002 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 曝光结束事件ID
        GX_INT_EVENT_EXPOSUREEND_TIMESTAMP = 8003 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 曝光结束事件时间戳
        GX_INT_EVENT_EXPOSUREEND_FRAMEID = 8004 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 曝光结束事件帧ID
        GX_INT_EVENT_BLOCK_DISCARD = 8005 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 数据块丢失事件ID
        GX_INT_EVENT_BLOCK_DISCARD_TIMESTAMP = 8006 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 数据块丢失事件时间戳
        GX_INT_EVENT_OVERRUN = 8007 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 事件队列溢出事件ID
        GX_INT_EVENT_OVERRUN_TIMESTAMP = 8008 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 事件队列溢出事件时间戳
        GX_INT_EVENT_FRAMESTART_OVERTRIGGER = 8009 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 触发信号被屏蔽事件ID
        GX_INT_EVENT_FRAMESTART_OVERTRIGGER_TIMESTAMP = 8010 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 触发信号被屏蔽事件时间戳
        GX_INT_EVENT_BLOCK_NOT_EMPTY = 8011 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 帧存不为空事件ID
        GX_INT_EVENT_BLOCK_NOT_EMPTY_TIMESTAMP = 8012 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 帧存不为空事件时间戳

        //---------------LUT Section-------------------------
        GX_ENUM_LUT_SELECTOR = 9000 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 查找表选择,参考GX_LUT_SELECTOR_ENTRY
        GX_BUFFER_LUT_VALUEALL = 9001 | GX_FEATURE_TYPE.BUFFER | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 查找表内容

        //---------------ChunkData Section-------------------------
        GX_BOOL_CHUNKMODE_ACTIVE = 10001 | GX_FEATURE_TYPE.BOOL | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 帧信息使能
        GX_ENUM_CHUNK_SELECTOR = 10002 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 帧信息项选择，参考GX_CHUNK_SELECTOR_ENTRY
        GX_BOOL_CHUNK_ENABLE = 10003 | GX_FEATURE_TYPE.BOOL | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 单项帧信息使能


        //////////////////////////////////////////////////////////////////////////
        /// 本地设备层(Device Feature)
        //////////////////////////////////////////////////////////////////////////
        GX_DEV_INT_COMMAND_TIMEOUT = 0 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DEV,

        ///< 命令超时
        GX_DEV_INT_COMMAND_RETRY_COUNT = 1 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DEV,

        ///< 命令重试次数

        //////////////////////////////////////////////////////////////////////////
        /// 流层(DataStream Feature)
        //////////////////////////////////////////////////////////////////////////
        GX_DS_INT_ANNOUNCED_BUFFER_COUNT = 0 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 声明的Buffer个数
        GX_DS_INT_DELIVERED_FRAME_COUNT = 1 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 接收帧个数(包括残帧)
        GX_DS_INT_LOST_FRAME_COUNT = 2 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< buffer不足导致的丢帧个数
        GX_DS_INT_INCOMPLETE_FRAME_COUNT = 3 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 接收的残帧个数
        GX_DS_INT_DELIVERED_PACKET_COUNT = 4 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 接收到的包数
        GX_DS_INT_RESEND_PACKET_COUNT = 5 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 重传包个数
        GX_DS_INT_RESCUED_PACKED_COUNT = 6 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 重传成功包个数
        GX_DS_INT_RESEND_COMMAND_COUNT = 7 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 重传命令次数
        GX_DS_INT_UNEXPECTED_PACKED_COUNT = 8 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 异常包个数
        GX_DS_INT_MAX_PACKET_COUNT_IN_ONE_BLOCK = 9 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 数据块最大重传包数
        GX_DS_INT_MAX_PACKET_COUNT_IN_ONE_COMMAND = 10 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 一次重传命令最大包含的包数
        GX_DS_INT_RESEND_TIMEOUT = 11 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 重传超时时间
        GX_DS_INT_MAX_WAIT_PACKET_COUNT = 12 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 最大等待包数
        GX_DS_ENUM_RESEND_MODE = 13 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.DS,

        ///< 重传模式,参考GX_DS_RESEND_MODE_ENTRY
        GX_DS_INT_MISSING_BLOCKID_COUNT = 14 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< BlockID丢失个数
        GX_DS_INT_BLOCK_TIMEOUT = 15 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 数据块超时时间
        GX_DS_INT_STREAM_TRANSFER_SIZE = 16 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 传输数据块大小
        GX_DS_INT_STREAM_TRANSFER_NUMBER_URB = 17 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 传输数据块数量
        GX_DS_INT_MAX_NUM_QUEUE_BUFFER = 18 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.DS,

        ///< 采集队列最大Buffer个数

        //////////////////////////////////////////////////////////////////////////
        /// 废弃区间段(Deprecated Section)
        //////////////////////////////////////////////////////////////////////////
        GX_STRING_DEVICE_ID = 4 | GX_FEATURE_TYPE.STRING | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 设备序列号[弃用，改用GX_STRING_DEVICE_SERIAL_NUMBER]	
        GX_STRING_DEVICE_HARDWARE_VERSION = 5 | GX_FEATURE_TYPE.STRING | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 设备硬件版本[弃用]
        GX_INT_GAIN = 5002 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 增益[弃用，改用GX_FLOAT_GAIN]
        GX_INT_BLACKLEVEL = 5005 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 黑电平[弃用，改用GX_FLOAT_BLACKLEVEL]
        GX_FLOAT_BALANCE_RATIO_SELECTOR = 5007 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 白平衡通道选择[弃用，改用GX_ENUM_BALANCE_RATIO_SELECTOR]
        GX_ENUM_AA_LIGHT_ENVIRMENT = 6007 | GX_FEATURE_TYPE.ENUM | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动曝光、自动增益，光照环境类型[弃用，改用GX_ENUM_AA_LIGHT_ENVIRONMENT]
        GX_INT_ROI_X = 6008 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动调节感兴趣区域X坐标[弃用，改用GX_INT_AAROI_OFFSETX]
        GX_INT_ROI_Y = 6009 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动调节感兴趣区域Y坐标[弃用，改用GX_INT_AAROI_OFFSETY]
        GX_INT_ROI_WIDTH = 6010 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动调节感兴趣区域宽度[弃用，改用GX_INT_AAROI_WIDTH]
        GX_INT_ROI_HEIGHT = 6011 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动调节感兴趣区域高度[弃用，改用GX_INT_AAROI_HEIGHT]
        GX_INT_AUTO_GAIN_VALUEMIN = 6012 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动增益最小值[弃用，改用GX_FLOAT_AUTO_GAIN_MIN]
        GX_INT_AUTO_GAIN_VALUEMAX = 6013 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动增益最大值[弃用，改用GX_FLOAT_AUTO_GAIN_MAX]
        GX_INT_AUTO_SHUTTER_VALUEMIN = 6014 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动曝光最小值[弃用，改用GX_FLOAT_AUTO_EXPOSURE_TIME_MIN]
        GX_INT_AUTO_SHUTTER_VALUEMAX = 6015 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 自动曝光最大值[弃用，改用GX_FLOAT_AUTO_EXPOSURE_TIME_MAX]
        GX_INT_CONTRASTPARAM = 6017 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 对比度参数[弃用，改用GX_INT_CONTRAST_PARAM]
        GX_FLOAT_GAMMAPARAM = 6018 | GX_FEATURE_TYPE.FLOAT | GX_FEATURE_LEVEL.REMOTE_DEV,

        ///< 伽马参数[弃用，改用GX_FLOAT_GAMMA_PARAM]
        GX_INT_COLORCORRECTIONPARAM = 6019 | GX_FEATURE_TYPE.INT | GX_FEATURE_LEVEL.REMOTE_DEV,
        ///< 颜色校正系数[弃用，改用GX_INT_COLOR_CORRECTION_PARAM]


    }
}
